spring:
  application:
    name: perudo-backend
  webflux:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
  web:
    resources:
      static-locations: classpath:/public/
    root: INFO
    com.perudo: DEBUG
